<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Quotations') }} - {{ $business->name }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #1a1a1a; line-height: 1.5; margin: 30px; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        .subtitle { color: #6b7280; margin-bottom: 20px; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #f3f4f6; text-align: left; padding: 7px 8px; font-size: 8px; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; border-bottom: 2px solid #e5e7eb; }
        th.right { text-align: right; }
        td { padding: 6px 8px; border-bottom: 1px solid #e5e7eb; }
        td.right { text-align: right; }
        .status-sent { color: #2563eb; font-weight: 700; }
        .status-accepted { color: #059669; font-weight: 700; }
        .status-converted { color: #6366f1; font-weight: 700; }
        .status-draft { color: #6b7280; }
        .status-rejected { color: #dc2626; }
        .footer { margin-top: 24px; font-size: 8px; color: #9ca3af; text-align: center; }
        .summary { margin-bottom: 16px; padding: 10px; background: #f9fafb; border-radius: 6px; font-size: 10px; }
        .summary strong { color: #374151; }
    </style>
</head>
<body>
    <h1>{{ __('Quotations') }}</h1>
    <div class="subtitle">{{ $business->name }} &mdash; {{ now()->format('F j, Y') }}</div>

    <div class="summary">
        <strong>{{ __('Total Quotations') }}:</strong> {{ $quotations->count() }} &nbsp;|&nbsp;
        <strong>{{ __('Total Amount') }}:</strong> UGX {{ number_format($quotations->sum('total'), 0) }}
    </div>

    <table>
        <thead>
            <tr>
                <th>{{ __('Number') }}</th>
                <th>{{ __('Customer') }}</th>
                <th>{{ __('Issue Date') }}</th>
                <th>{{ __('Valid Until') }}</th>
                <th class="right">{{ __('Total') }}</th>
                <th>{{ __('Status') }}</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($quotations as $quotation)
                <tr>
                    <td>{{ $quotation->quotation_number }}</td>
                    <td>{{ $quotation->customer?->name ?? __('Walk-in') }}</td>
                    <td>{{ $quotation->issue_date->format('d M Y') }}</td>
                    <td>{{ $quotation->valid_until?->format('d M Y') ?? '—' }}</td>
                    <td class="right">UGX {{ number_format($quotation->total, 0) }}</td>
                    <td class="status-{{ $quotation->status }}">{{ ucfirst($quotation->status) }}</td>
                </tr>
            @empty
                <tr><td colspan="6" style="text-align:center;padding:30px;color:#9ca3af;">{{ __('No quotations found.') }}</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        {{ __('Generated by :app on :date', ['app' => config('app.name'), 'date' => now()->format('Y-m-d H:i:s')]) }}
    </div>
</body>
</html>